package entity;
// Generated Nov 5, 2018 11:02:08 AM by Hibernate Tools 4.3.1



/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private Integer cid;
     private String courseName;
     private Integer courseHours;
     private Double fees;
     private String batchName;
     private Integer module;
     private String schedule;

    public Course() {
    }

    public Course(String courseName, Integer courseHours, Double fees, String batchName, Integer module, String schedule) {
       this.courseName = courseName;
       this.courseHours = courseHours;
       this.fees = fees;
       this.batchName = batchName;
       this.module = module;
       this.schedule = schedule;
    }
   
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }
    public String getCourseName() {
        return this.courseName;
    }
    
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }
    public Integer getCourseHours() {
        return this.courseHours;
    }
    
    public void setCourseHours(Integer courseHours) {
        this.courseHours = courseHours;
    }
    public Double getFees() {
        return this.fees;
    }
    
    public void setFees(Double fees) {
        this.fees = fees;
    }
    public String getBatchName() {
        return this.batchName;
    }
    
    public void setBatchName(String batchName) {
        this.batchName = batchName;
    }
    public Integer getModule() {
        return this.module;
    }
    
    public void setModule(Integer module) {
        this.module = module;
    }
    public String getSchedule() {
        return this.schedule;
    }
    
    public void setSchedule(String schedule) {
        this.schedule = schedule;
    }




}


