package entity;
// Generated Nov 5, 2018 11:02:08 AM by Hibernate Tools 4.3.1



/**
 * Schedule generated by hbm2java
 */
public class Schedule  implements java.io.Serializable {


     private Integer schid;
     private String scheduleName;

    public Schedule() {
    }

    public Schedule(String scheduleName) {
       this.scheduleName = scheduleName;
    }
   
    public Integer getSchid() {
        return this.schid;
    }
    
    public void setSchid(Integer schid) {
        this.schid = schid;
    }
    public String getScheduleName() {
        return this.scheduleName;
    }
    
    public void setScheduleName(String scheduleName) {
        this.scheduleName = scheduleName;
    }




}


