package entity;
// Generated Nov 5, 2018 11:02:08 AM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer uid;
     private String username;
     private String uemail;
     private String upassword;
     private Integer uroleid;

    public User() {
    }

    public User(String username, String uemail, String upassword, Integer uroleid) {
       this.username = username;
       this.uemail = uemail;
       this.upassword = upassword;
       this.uroleid = uroleid;
    }
   
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getUemail() {
        return this.uemail;
    }
    
    public void setUemail(String uemail) {
        this.uemail = uemail;
    }
    public String getUpassword() {
        return this.upassword;
    }
    
    public void setUpassword(String upassword) {
        this.upassword = upassword;
    }
    public Integer getUroleid() {
        return this.uroleid;
    }
    
    public void setUroleid(Integer uroleid) {
        this.uroleid = uroleid;
    }




}


